const [HOST, HOOKCOMPONENT, CLASSCOMPONENT, HOSTROOT] = [0, 1, 2, 3]
const [NormalPriority] = [97]


const [DELETE, UPDATE, PLACEMENT] = [2, 3, 4]

export {HOST,HOOKCOMPONENT,CLASSCOMPONENT,HOSTROOT,DELETE,UPDATE,PLACEMENT,NormalPriority}