const [HOST, HOOKCOMPONENT, CLASSCOMPONENT, HOSTROOT] = [0, 1, 2, 3]
const [NormalPriority] = [97]

const [NOWORK, DELETE, UPDATE, PLACEMENT] = [0, 2, 3, 4]

export {
  HOST,
  HOOKCOMPONENT,
  CLASSCOMPONENT,
  HOSTROOT,
  NOWORK,
  DELETE,
  UPDATE,
  PLACEMENT,
  NormalPriority
}
